### ISSUE TITLE
Order API returning bad request

### ISSUE THREAD

**Issue by lovelovelovelovelovelovelove** [zandoan/turing-frontend#13]
![Screenshot (64)](https://user-images.githubusercontent.com/29616003/55044321-802ce400-5042-11e9-8ebf-779b7a0079c1.png)
![Screenshot (65)](https://user-images.githubusercontent.com/29616003/55044326-84590180-5042-11e9-95f9-9178a8a135b3.png)
I have attached pictures of the issues

**Comment by edertaveiraturing** [comment]
Hi dear, 
You need first do a login (customer/login) and get the API CODE generated in this request, so after that, you need put this code in the request that needs authorization, like the image attached.

In your application, you need to put this information in the header, check more attentively the documentation authorization to do it correctly.

Good luck.
![Screen Shot 2019-03-26 at 22 54 21](https://user-images.githubusercontent.com/48455101/55044750-4ba53200-501a-11e9-898d-63d6d37fe4d3.png)

**Comment by lovelovelovelovelovelovelove** [comment]
I see, lemme try that, Thank you
