### ISSUE TITLE
POST request for customers/login not working?

### ISSUE THREAD

**Issue by bernarddoci** [zandoan/turing-frontend#17]
I have serialized object for post request as it its on documentation and the response that I am getting is 204 and (canceled), I think that CORS should  be allow for javascript on the backend side.

**Comment by edertaveiraturing** [comment]
Hi Bernard.
 I've test here and worked good.
Please, check this images from Swagger and Postman and the CURL code below.

```
curl -X POST "https://backendapi.turing.com/customers/login" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "email=edertaveira%40gmail.com&password=santos123"
```

![Screen Shot 2019-04-05 at 19 19 25](https://user-images.githubusercontent.com/48455101/55659452-1c3fb380-57d8-11e9-83ae-ebfd7d4aca81.png)
![Screen Shot 2019-04-05 at 19 20 46](https://user-images.githubusercontent.com/48455101/55659453-1c3fb380-57d8-11e9-85ae-55a59d5105a6.png)

**Comment by bernarddoci** [comment]
Hi Edert, 

I have tested with Postman to, it works but Postman has some other headers which can bypass CORS, after that I have tested from the browser with a plugin that bypass CORS and it returned status 200 but without response data and after research that I have made it appears that this problem is related to a CORS. 

I think that you should enable CORS because JavaScript frameworks may depend on the jQuery XHR object, which must be configured properly to allow Cross-Origin requests.

**Comment by edertaveiraturing** [comment]
Bernard, what's your email?

**Comment by bernarddoci** [comment]
bernard.doci@gmail.com

**Comment by bernarddoci** [comment]
Hi Edert,

Post request is still not working. 
Can you please help me because I am still stuck with register and login, can't move forward without a token key.

**Comment by edertaveiraturing** [comment]
Hi Bernard. 
Could you, please, send your code request to eder.t@turing.com.

**Comment by bernarddoci** [comment]
Hi Edert,
I have sent you an email.

**Comment by bernarddoci** [comment]
Hi Edert,
Please can you check the api for ReactJS Cors again because I have tried other web apis with axios post and they work fine, I am encountering this problem only with post requests in https://backendapi.turing.com/.

**Comment by bernarddoci** [comment]
All good now
