### ISSUE TITLE
Internal server error on stripe charge

### ISSUE THREAD

**Issue by DanielNgozika** [zandoan/turing-frontend#26]
The server returns this error message: "No such token: tok_1EYaVXEvTdlf0Dy6OHCAm98M" when I make a POST request to the /stripe/charge API. The token was returned by stripe.

It might be worth mentioning that I am using my stripe test publishable token. Am I doing anything wrong?

**Comment by edertaveiraturing** [comment]
How do you are doing to get that token?

**Comment by DanielNgozika** [comment]
By running this code: 
submit = async ev => {
  ...
  let { token } = await this.props.stripe.createToken({ name: "Name" })
  ...
}

I then pass token.id returned to the stripe/charge API as part of the body data.

**Comment by DanielNgozika** [comment]
I've fixed it. I used Turing's Stripe publishable token as indicated on the Github page instead of mine.
