### ISSUE TITLE
api update Profile error

### ISSUE THREAD

**Issue by aleksh** [zandoan/turing-frontend#34]
backendapi.turing.com/customers:1 PUT https://backendapi.turing.com/customers 404 (Not Found)
profile:1 Access to XMLHttpRequest at 'https://backendapi.turing.com/customers' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by edertaveiraturing** [comment]
Hi Aleksh, the correct endpoint to update a customer is [PUT](https://backendapi.turing.com/customer) https://backendapi.turing.com/customer
Try to use that and let me know about.

**Comment by aleksh** [comment]
Hi EderTaveiraturing
Works thanks
