### ISSUE TITLE
Facebook Login Error

### ISSUE THREAD

**Issue by aleksh** [zandoan/turing-frontend#35]
Login Facebook Error 
When I use my out facebook app Id  I can get response from facebook 
but then I have error from facebookLogin turing api

When I use turin facebook app Id  I have facebook error
We found that the Turing Web Challange application cannot provide a secure data connection.

**Comment by edertaveiraturing** [comment]
Please share the error and the code as well.

**Comment by aleksh** [comment]
I use "react-facebook" package

```
<FacebookProvider appId="352854622106208">
   <LoginButton 
		scope="email"
		onCompleted={this._handleFacebookResponse}
		onError={this._handleFacebookError}>
		<span>Login via Facebook</span>
 </LoginButton>
</FacebookProvider>
```

In browser  console I see an error 
index.js:1375 The method FB.login can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

_handleFacebookError  get Error: Unauthorized user

**Comment by edertaveiraturing** [comment]
Do you are using HTTPS or HTTP to test?

**Comment by aleksh** [comment]
ah I used http 
works now thanks
