### ISSUE TITLE
Authorization issues when updating profile

### ISSUE THREAD

**Issue by kevinrblake** [zandoan/turing-frontend#37]
I'm having issues updating profiles. I keep getting a 401Unauthorized.

My headers look like this: 
{"Authorization":"USER-KEY eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6MTUyMzUsIm5hbWUiOiJrZXZpbiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTU2MTY3ODU4MywiZXhwIjoxNTYxNzY0OTgzfQ.7SzTHRNOtIGxudMHi8-2qjaPWYSrN_6Nd2W5xXhaD6E"}

I've also tried Bearer in the place of USER-KEY with the same results, I got the impression from the Swagger that I needed to use USER-KEY.  Is there anything that I am missing? Am I formatting it incorrectly?

**Comment by edertaveiraturing** [comment]
Hi Kevin, please read the Authentication session on this link: 
https://github.com/zandoan/turing-frontend

**Comment by kevinrblake** [comment]
Hrm, I read that before, but it was a week ago.  I suppose my first step should be to go back to the documentation. Thanks for the prompt response.
