### ISSUE TITLE
Stripe/charge is returning "{"error":{"code":"missing_payment_information","message":"Could not find payment information"}}"

### ISSUE THREAD

**Issue by kevinrblake** [zandoan/turing-frontend#38]
Using one of Stripe's test CC#'s.  I get back the error in the title, I am setting a CC and am creating a stripe token successfully.

My request JSON looks like this: ```
{
amount: 1999

currency: "USD"

description: "Products: Arc d'Triomphe: {"color":" White","size":"L"}, "

order_id: 15853

stripeToken: {client_ip: "75.130.219.31"
     created: 1561746437
     id: "tok_1EqOn3AeyoDrBLzKZNzALdGD"
     livemode: false
     object: "token"
     type: "card"
     used: false
     card: {
        address_city: null
        address_country: null
        address_line1: null
       address_line1_check: null
       address_line2: null
       address_state: null
       address_zip: "42424"
       address_zip_check: "unchecked"
       brand: "Visa"
      country: "US"
      cvc_check: "unchecked"
      dynamic_last4: null
      exp_month: 4
      exp_year: 2024
      funding: "credit"
     id: "card_1EqOn3AeyoDrBLzKKJTVJmS0"
      last4: "4242"
      metadata: {}
      name: "Kevin"
      object: "card"
     tokenization_method: null}
}```

**Comment by edertaveiraturing** [comment]
Hi Kevin, please check the documentation about Stripe here https://github.com/zandoan/turing-frontend, and the stripe documentation here https://stripe.com/docs/stripe-js/elements/quickstart to check the params.

**Comment by kevinrblake** [comment]
Neither the swagger nor either piece of documentation is clear that the stripeToken is only the token id generated when creating a token and not the entire token. Issue resolved.

**Comment by vhcoder** [comment]
OK--- this is the exact problem I am seeing (using a test card), and I seem to be following the documentation to the 'T'.
Payload:
```
{
  "amount": "12000",
  "currency": "usd",
  "source": {
    "id": "tok_1FfXfqElWTrUMVb5X6jrQvq5",
    "object": "token",
    "card": {
      "id": "card_1FfXfqElWTrUMVb5M03spgkR",
      "object": "card",
      "address_city": "",
      "address_country": "",
      "address_line1": "",
      "address_line1_check": "",
      "address_line2": "",
      "address_state": "",
      "address_zip": "",
      "address_zip_check": "",
      "brand": "Visa",
      "country": "US",
      "cvc_check": "unchecked",
      "dynamic_last4": "",
      "exp_month": "1",
      "exp_year": "2020",
      "funding": "credit",
      "last4": "4242",
      "name": "Test User",
      "tokenization_method": ""
    },
    "client_ip": "3.83.183.159",
    "created": "1573935314",
    "livemode": "false",
    "type": "card",
    "used": "false"
  },
  "description": "payment for class"
}

```
Response:
```
{
  "error": {
    "code": "missing_payment_information",
    "message": "Could not find payment information",
    "type": "invalid_request_error"
  }
}
```
Must be missing something obvious-- any help would be appreciated... and yes, I have read the documentation being referred to above. 

Thank you!

**Comment by vhcoder** [comment]
Well, figured out like the previous poster. Leaving a less cryptic message about the issue for those who follow the same path:
1) Do not pass in the full token you get back from Stripe. The stripeToken is in fact just the token.id from the token object you get back from Stripe. That is all Stripe needs to process the information. More is in fact bad.
2) Do not stringify the JSON you are posting. That was error#2 for me- from some unnamed post. Send the JSON object as is when sending the tokenId. 
Best of lucks!
